[sheets]
#실적분석
f_1 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT6-MqS2TLscLpV_uASLMb6j1ZlLYv0adVK5dtz4QUgmwheywGLRk7bvBK7wzNrbQ/pub?gid=661636528&single=true&output=csv"
f_2 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQiH6OPJ7mRpELeifYuI8Fl9Yryhpo2Nn1Y8DO0qlWkT_ZdGt-cA67pJ7oz4g5DvA/pub?gid=1395939598&single=true&output=csv"
f_3 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSwE0_-nIrY_2WC0JO0IAFAyA7ercbgXTjrlicAt5-Alio8hq9u4YpD_Z5R2ZeJtg/pub?gid=644206477&single=true&output=csv"
f_4 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQFxWqbs3nqCbK_Uclhcet5RJtPHiWxavMMObd3vp7blpvvt3C5d0E7XMm4I3O5yQ/pub?gid=1831626571&single=true&output=csv"
f_5 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQcUAor_HKi1uddHYndagLozMMYtNTwRMKYyfCtgeApgoLNhvALFne0c0PdAv7UlA/pub?gid=1677430502&single=true&output=csv"
f_7 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRPg4MecSPX0Fk6Mxp44d2PT8LGSUdYTg5k012zxEfDNRWfTz72YMv35FuTUTXYCQ/pub?gid=425097731&single=true&output=csv"
f_8 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS1EBG1b5MAx6YO8bLUtfTPLJ9RFsT7WdWS_m4qzD8nl1DpbE-F0GGrwtSCTPhD1g/pub?gid=1632728904&single=true&output=csv"

f_11 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS26eQCJvxP4CM_RDiY85-U47RdwoUykfOdZzZYXWY-ptsQAahMRvsvpmCzm7btsQ/pub?gid=689725974&single=true&output=csv"
f_12 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTM4aId_54jjk0C6nMJYJiYQiQ_hEPMsig3nxNbsaTBQ1etk6SXYhvXdQevXRdy7w/pub?gid=995470671&single=true&output=csv"
f_13 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSwE0_-nIrY_2WC0JO0IAFAyA7ercbgXTjrlicAt5-Alio8hq9u4YpD_Z5R2ZeJtg/pub?gid=644206477&single=true&output=csv"

#손익분석
f_19 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTqsKj1vBNiTG2LkvDkdACDqB4SzPz9qtbtu4BaIt2gGNGWSwF4QxjosW2X20Fl2A/pub?gid=1826701987&single=true&output=csv"

#매출
f_30 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=1128710783&single=true&output=csv"
f_31 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=687154753&single=true&output=csv"
f_32 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=231872479&single=true&output=csv"
f_33 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=100449631&single=true&output=csv"
f_34 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=81576201&single=true&output=csv"
f_35 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=760145087&single=true&output=csv"
f_36 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=454664806&single=true&output=csv"
f_37 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=411667777&single=true&output=csv"
f_38_1 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=2082357859&single=true&output=csv"
f_38_2 ="https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=648797519&single=true&output=csv"

#생산

f_40 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSWVbBpLZ8gYUHNKB25rp_wMKFm8jhxT9JsBq2ihrfiuxbVbmYsjLLmZbRWU9Z-wg/pub?gid=2134042743&single=true&output=csv"
f_41_42 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSWVbBpLZ8gYUHNKB25rp_wMKFm8jhxT9JsBq2ihrfiuxbVbmYsjLLmZbRWU9Z-wg/pub?gid=475831306&single=true&output=csv"

#비용-클레임
f_43 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSNzd_NnmhHvc9Q_XMoqQDAvr9ofjFKs84nTdPtO_CiG_UrrgQOLQ_QH0UDMbdwYg/pub?gid=98848050&single=true&output=csv"
f_46 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQlO8x2fDt4tne6JULBUAnEghgrz21XAjnzZ06idc3maf8NPNSIESu4s32tD7W7pA/pub?gid=948260720&single=true&output=csv"
f_47 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRTyKU27WElbZSIfCoLPCEtdkCJw0M9mTchlb8LzaFoAenM7hY7Oq0aRumfAis0NA/pub?gid=1809148235&single=true&output=csv"
f_48 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRTyKU27WElbZSIfCoLPCEtdkCJw0M9mTchlb8LzaFoAenM7hY7Oq0aRumfAis0NA/pub?gid=1916788416&single=true&output=csv"
f_49 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRTyKU27WElbZSIfCoLPCEtdkCJw0M9mTchlb8LzaFoAenM7hY7Oq0aRumfAis0NA/pub?gid=1291824453&single=true&output=csv"

#재고
f_50 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS-LNd2FpTCvaSfsxRKbsTSNoUhdrDsP3jl-M1K9yvQ8Yhej5OdYiAeMohfrREiMg/pub?gid=329797563&single=true&output=csv"
f_51 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS-LNd2FpTCvaSfsxRKbsTSNoUhdrDsP3jl-M1K9yvQ8Yhej5OdYiAeMohfrREiMg/pub?gid=1683168804&single=true&output=csv"
f_52 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS-LNd2FpTCvaSfsxRKbsTSNoUhdrDsP3jl-M1K9yvQ8Yhej5OdYiAeMohfrREiMg/pub?gid=2102591981&single=true&output=csv"

#별첨
f_89 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTQMzIy09V0sERNZOSI75AhwqamxGxnMPYpw3mHew6_CNfo_uRrtpC4yuyAu6IuAA/pub?gid=89164240&single=true&output=csv"
f_93 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTQMzIy09V0sERNZOSI75AhwqamxGxnMPYpw3mHew6_CNfo_uRrtpC4yuyAu6IuAA/pub?gid=1435491061&single=true&output=csv"
f_94 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTQMzIy09V0sERNZOSI75AhwqamxGxnMPYpw3mHew6_CNfo_uRrtpC4yuyAu6IuAA/pub?gid=346819390&single=true&output=csv"

[memos]
f_30 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=639178020&single=true&output=csv"
f_31 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=636597764&single=true&output=csv"
f_32 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=156854746&single=true&output=csv"
f_33 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=612029069&single=true&output=csv"
f_34 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=379955021&single=true&output=csv"
f_35 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=385842314&single=true&output=csv"
f_36 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=1196469258&single=true&output=csv"
f_37 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgKuPFyrj7J_46EszSMk4KTuk6IlFGBJvn4hpPj2kuYR_xcTgAfbEyI-iVR_xPQ/pub?gid=1461008155&single=true&output=csv"
f_19 = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTqsKj1vBNiTG2LkvDkdACDqB4SzPz9qtbtu4BaIt2gGNGWSwF4QxjosW2X20Fl2A/pub?output=csv"